### ISSUE TITLE
Semana cuatro

### ISSUE THREAD

**Issue by agusces0** [CodeSystem2022/YoungDevelopers2023#4]
Continuando con el proyecto tenemos que organizar y subir los ejercicios correspondiente a la semana cuatro de las materias, Programación 3 y Laboratorio 3, abajo una lista de tareas.

- [x] Ejercicios correspondientes a JavaScript de la cuarta semana.
- [x] Ejercicios correspondientes a Java de la cuarta semana.
- [x] Ejercicios correspondientes a Python de la cuarta semana.

**Comment by lulyrp** [comment]
Cargamos de forma exitosa todos los ejercicios de la semana.
